### PR TITLE
breaking: Update play-json to `2.8.2`

### PR DESCRIPTION
**Pull request by lucassklp**
Drop support for Scala 2.10 and 2.11

### CODE REVIEW

**Comment by lolgab** [comment]
Can you check what component uses this library? Because if a component using play uses it there might be classpath problems, since they use Play 2.7

**Comment by lucassklp** [comment]
[The current version of play-json depends on a outdated version of jackson that have a lot of vulnerabilities](https://mvnrepository.com/artifact/com.typesafe.play/play-json_2.12/2.6.10). [This update](https://mvnrepository.com/artifact/com.typesafe.play/play-json_2.13/2.8.2) aims to reduce the amount of vulnerabilities caused by outdated libraries like https://github.com/codacy/codacy-coverage-reporter/issues/372

**Comment by lolgab** [comment]
Was this backported to 2.7 maybe @lucassklp ?

**Comment by lucassklp** [comment]
It was not @lolgab . If we check out the latest version of 2.7 which is [2.7.4](https://mvnrepository.com/artifact/com.typesafe.play/play-json_2.13/2.7.4 ) we see the 
 high amout of vulnerabilities

**Comment by lucassklp** [comment]
I may be wrong [but the only dependency](https://github.com/search?q=org%3Acodacy+codacy-api-scala&type=code) of this library is on codacy-coverage-reporter, which is our goal to update

**Review by lolgab — APPROVED** [review]

**Pull request merged**
